// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBioFul_s9pUj2svrzF0uFqOq2_TTrZzhI',
    appId: '1:471877121168:web:fa06d85f513c8c93449415',
    messagingSenderId: '471877121168',
    projectId: 'ecommerceapp-bf4b3',
    authDomain: 'ecommerceapp-bf4b3.firebaseapp.com',
    databaseURL: 'https://ecommerceapp-bf4b3-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-bf4b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhreeBdVTc3m1J-_dTRWXfqgDzs5Bl7BA',
    appId: '1:471877121168:android:6546d5a45ceea1c1449415',
    messagingSenderId: '471877121168',
    projectId: 'ecommerceapp-bf4b3',
    databaseURL: 'https://ecommerceapp-bf4b3-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-bf4b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ5imKmjyXQGkxQCQFXOpkokJuGgVl4Zo',
    appId: '1:471877121168:ios:4516f7ebb6db8467449415',
    messagingSenderId: '471877121168',
    projectId: 'ecommerceapp-bf4b3',
    databaseURL: 'https://ecommerceapp-bf4b3-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-bf4b3.appspot.com',
    androidClientId: '471877121168-5lsnp0cj67cnih17c15hpmm4rjvo9d5v.apps.googleusercontent.com',
    iosClientId: '471877121168-cjlpcug3unef6r51b56b7q34dctr4db1.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ5imKmjyXQGkxQCQFXOpkokJuGgVl4Zo',
    appId: '1:471877121168:ios:acc81c1b0ebf7b8d449415',
    messagingSenderId: '471877121168',
    projectId: 'ecommerceapp-bf4b3',
    databaseURL: 'https://ecommerceapp-bf4b3-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-bf4b3.appspot.com',
    androidClientId: '471877121168-5lsnp0cj67cnih17c15hpmm4rjvo9d5v.apps.googleusercontent.com',
    iosClientId: '471877121168-gkco99rg2atsl7vlqa8cm7ebgorlensv.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping.RunnerTests',
  );
}
